changed the build folder to CIDI to not get mixed in with the git ignore

diff --git a/.github/workflows/upload_production.yml b/.github/workflows/upload_production.yml
--- a/.github/workflows/upload_production.yml
+++ b/.github/workflows/upload_production.yml
@@ -13,24 +13,31 @@ jobs:
         channel: [production]
 
     steps:
+      - name: Verify build directory
+        run: |
+          if [ ! -d "build/WebGL" ]; then
+            echo "Directory not found!"
+            exit 1
+          fi
+
       - name: Cache WebGl build
         uses: actions/cache@v2
         with:
-          path: build/WebGL
+          path: CICD/WebGL
           key: ${{ runner.os }}-build-webgl-${{ matrix.template }}
           restore-keys: |
             ${{ runner.os }}-build-webgl-${{ matrix.template }}
 
       - name: Display structure of root files
         run: ls -R
-        working-directory: build/WebGL
+        working-directory: CICD/WebGL
 
       - name: Upload to Itch
         if: steps.cache.outputs.cache-hit != 'true'
         uses: KikimoraGames/itch-publish@v0.0.3
         with:
           butlerApiKey: ${{ secrets.ITCH_IO_API_KEY }}
-          gameData: ./build/${{ matrix.template }}
+          gameData: ./CICD/${{ matrix.template }}
           itchUsername: ${{ env.ITCH_USERNAME }}
           itchGameId: ${{ env.ITCH_GAME_ID }}
           buildChannel: ${{ matrix.channel }}
